ProjectManager.UI/Controllers/SubContractorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Application.Common.Interfaces;
using ProjectManager.Application.Dictionaries;
using ProjectManager.Application.SubContractors.Commands.AddSubContractor;
using ProjectManager.Application.SubContractors.Commands.DeleteSubContractor;
using ProjectManager.Application.SubContractors.Commands.EditSubContractor;
using ProjectManager.Application.SubContractors.GetSubContractorBasics;
using ProjectManager.Application.SubContractors.Queries.GetEditSubContractor;

namespace ProjectManager.UI.Controllers
{
    [Authorize(Roles = $"{RolesDict.Pracownik},{RolesDict.Administrator}")]
    public class SubContractorController : BaseController
    {
        private readonly IDateTimeService _dateTimeService;
        private readonly ILogger<ClientController> _logger;

        public SubContractorController(IDateTimeService dateTimeService,
                                ILogger<ClientController> logger)
        {
            _dateTimeService = dateTimeService;
            _logger = logger;
        }

        public async Task<IActionResult> SubContractors()
        {
            return View(await Mediator.Send(new GetSubContractorBasicsQuery()));
        }

        public async Task<IActionResult> AddSubContractor()
        {
            return View(new AddSubContractorCommand());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSubContractor(AddSubContractorCommand command)
        {
            var result = await MediatorSendValidate(command);

            if (!result.IsValid)
                return View(command);

            TempData["Success"] = "Podwykonawca został dodany.";

            return RedirectToAction("SubContractors");
        }

        public async Task<IActionResult> EditSubContractor(int Id)
        {
            return View(await Mediator.Send(new GetEditSubContractorQuery { Id = Id }));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSubContractor(EditSubContractorCommand command)
        {
            var result = await MediatorSendValidate(command);

            if (!result.IsValid)
                return View(command);

            TempData["Success"] = "Dane podwykonawcy zostały zaktualizowane.";

            return RedirectToAction("SubContractors");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSubContractor(int id)
        {
            try
            {
                await Mediator.Send(
                    new DeleteSubContractorCommand
                    {
                        Id = id
                    });

                return Json(new { success = true });
            }
            catch (Exception exception)
            {
                _logger.LogError(exception, null);
                return Json(new { success = false });
            }
        }
    }

}

ProjectManager.UI/Views/Basic/SubContractor/AddSubContractor.cshtml
@using ProjectManager.Application.SubContractors.Commands.AddSubContractor


@model AddSubContractorCommand

@{
    ViewData["Title"] = "Dodawanie nowego podwykonawcy";
}

<div class="card card-primary card-border-top">

    @using (Html.BeginForm("AddSubContractor", "SubContractor"))
    {
        @Html.AntiForgeryToken()

        <div class="card-body">

            <div class="form-group">
                @Html.LabelFor(x => x.Email)
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder="Wprowadź e-mail"})
                @Html.ValidationMessageFor(x => x.Email)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder="Wprowadź nazwę"})
                @Html.ValidationMessageFor(x => x.Name)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.ContactPerson)
                @Html.TextBoxFor(x => x.ContactPerson, new { @class = "form-control", placeholder="Wprowadź osobę do kontaktu"})
                @Html.ValidationMessageFor(x => x.ContactPerson)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.PhoneNumber)
                @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control", placeholder="Wprowadź numer telefonu"})
                @Html.ValidationMessageFor(x => x.PhoneNumber)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.City)
                @Html.TextBoxFor(x => x.City, new { @class = "form-control", placeholder="Wprowadź miejscowość"})
                @Html.ValidationMessageFor(x => x.City)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.ZipCode)
                @Html.TextBoxFor(x => x.ZipCode, new { @class = "form-control", placeholder="Wprowadź kod pocztowy"})
                @Html.ValidationMessageFor(x => x.ZipCode)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Street)
                @Html.TextBoxFor(x => x.Street, new { @class = "form-control", placeholder="Wprowadź ulicę"})
                @Html.ValidationMessageFor(x => x.Street)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.StreetNumber)
                @Html.TextBoxFor(x => x.StreetNumber, new { @class = "form-control", placeholder="Wprowadź numer domu"})
                @Html.ValidationMessageFor(x => x.StreetNumber)
            </div>

        </div>

        <div class="card-footer">
             <button type="submit" class="btn btn-primary btn-lg">
                <i class="fas fa-solid fa-circle-check"></i>Zapisz
            </button>
        </div>

    }

</div>


@section Scripts {

    <partial name="Scripts/_ValidationScriptsPartial" />

    <script src="~/lib/inputmask/jquery.inputmask.bundle.min.js"></script>

    <script>
        $(document).ready(function() {


            $("#ZipCode").inputmask("99-999", { "clearIncomplete": true, showMaskOnHover: false });

        });

        });

    </script>
}

ProjectManager.UI/Views/Basic/SubContractor/EditSubContractor.cshtml
@using ProjectManager.Application.SubContractors.Commands.EditSubContractor


@model EditSubContractorCommand

@{
    ViewData["Title"] = "Edytowanie klienta";
}

<div class="card card-primary card-border-top">

    @using (Html.BeginForm("EditSubContractor", "SubContractor"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x=>x.Id)

        <div class="card-body">

            <div class="form-group">
                @Html.LabelFor(x => x.Email)
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder="Wprowadź e-mail"})
                @Html.ValidationMessageFor(x => x.Email)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder="Wprowadź nazwę"})
                @Html.ValidationMessageFor(x => x.Name)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.ContactPerson)
                @Html.TextBoxFor(x => x.ContactPerson, new { @class = "form-control", placeholder="Wprowadź osobę do kontaktu"})
                @Html.ValidationMessageFor(x => x.ContactPerson)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.PhoneNumber)
                @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control", placeholder="Wprowadź numer telefonu"})
                @Html.ValidationMessageFor(x => x.PhoneNumber)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.City)
                @Html.TextBoxFor(x => x.City, new { @class = "form-control", placeholder="Wprowadź miejscowość"})
                @Html.ValidationMessageFor(x => x.City)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.ZipCode)
                @Html.TextBoxFor(x => x.ZipCode, new { @class = "form-control", placeholder="Wprowadź kod pocztowy"})
                @Html.ValidationMessageFor(x => x.ZipCode)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Street)
                @Html.TextBoxFor(x => x.Street, new { @class = "form-control", placeholder="Wprowadź ulicę"})
                @Html.ValidationMessageFor(x => x.Street)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.StreetNumber)
                @Html.TextBoxFor(x => x.StreetNumber, new { @class = "form-control", placeholder="Wprowadź numer domu"})
                @Html.ValidationMessageFor(x => x.StreetNumber)
            </div>

        </div>

        <div class="card-footer">
             <button type="submit" class="btn btn-primary btn-lg">
                <i class="fas fa-solid fa-circle-check"></i>Zapisz
            </button>
        </div>

    }

</div>


@section Scripts {

    <partial name="Scripts/_ValidationScriptsPartial" />

    <script src="~/lib/inputmask/jquery.inputmask.bundle.min.js"></script>

    <script>
        $(document).ready(function() {


            $("#ZipCode").inputmask("99-999", { "clearIncomplete": true, showMaskOnHover: false });

        });

        });

    </script>
}

ProjectManager.UI/Views/Basic/SubContractor/SubContractors.cshtml
@using System.Globalization
@using ProjectManager.Application.SubContractors.Queries.GetSubContractorBasics

@model IEnumerable<SubContractorBasicsDto>

@{
    ViewData["Title"] = "Podwykonawcy";
    var locale = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
}

@section Styles {
    <partial name="Styles/_DataTablesStyles" />
}

<partial name="Modals/_ModalConfirm"
         model="@(new ModalParams
         {
             Id = "modal-confirm-delete",
             Title = "Potwierdź proszę",
             Description = "Czy na pewno chcesz usunąć wybranego podwykonawcę?"
         })" />

<div class="card card-primary card-border-top">

    <div class="card-header d-flex justify-content-between align-items-center">
        <h3 class="card-title mb-0">
            <i class="fas fa-users-gear me-2"></i>Lista podwykonawców
        </h3>

        <a href="/SubContractor/AddSubContractor" class="btn btn-primary">
            <i class="fas fa-circle-plus me-1"></i>Dodaj podwykonawcę
        </a>
    </div>

    <div class="card-body">

        <table id="subContractors" class="table table-hover table-striped align-middle">
            <thead class="table-light">
                <tr>
                    <th>Nazwa podwykonawcy</th>
                    <th>Osoba do kontaktu</th>
                    <th class="text-end desktop">Akcje</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var subContractor in Model)
                {
                    <tr>
                        <td>
                            <a class="edit-link fw-semibold"
                               href="/SubContractor/EditSubContractor?id=@subContractor.Id">
                                <i class="fas fa-building me-1 text-primary"></i>
                                @subContractor.Name
                            </a>
                        </td>

                        <td>
                            <i class="fas fa-user-tie me-1 text-secondary"></i>
                            @subContractor.ContactPerson
                        </td>

                        <td class="text-end">

                            <a class="btn btn-success btn-sm me-1"
                               href="/SubContractor/EditSubContractor?id=@subContractor.Id">
                                <i class="fas fa-pen-to-square me-1"></i>Edytuj
                            </a>

                            <button class="btn btn-danger btn-sm"
                                    onclick="deleteSubContractor('@subContractor.Id', this)">
                                <i class="fas fa-trash-can me-1"></i>Usuń
                            </button>

                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

</div>

@section Scripts {
    <partial name="Scripts/_DataTablesScripts" />

    <script>

        let selectedRow;
        let selectedsubContractorId = 0;
        let subContractors;

        $(document).ready(function () {

            subContractors = $('#subContractors').DataTable({
                paging: true,
                ordering: true,
                info: true,
                responsive: true,
                autoWidth: false,
                lengthChange: true,
                language: {
                    url: `/lib/datatables/lang/${'@locale'}.json`
                },
                order: [[0, "asc"]],
                columnDefs: [
                    { targets: -1, orderable: false }
                ]
            });

        });

        function deleteSubContractor(id, btn) {
            selectedRow = btn.closest('tr');
            selectedsubContractorId = id;
            $('#modal-confirm-delete').modal('show');
        }

        $('#modal-confirm-delete-btn').on('click', function () {

            $('#modal-confirm-delete').modal('hide');

            $.ajax({
                type: "POST",
                url: "/SubContractor/DeleteSubContractor",
                data: { id: selectedsubContractorId },
                dataType: "json",
                success: function (data) {
                    if (data.success) {
                        subContractors.row(selectedRow).remove().draw();
                        toastr.success('Podwykonawcy zostali zaktualizowani.');
                    } else {
                        toastr.error('Błąd. ' + data.message);
                    }
                },
                error: function () {
                    toastr.error('Błąd. Nie udało się usunąć wybranego podwykonawcy. Spróbuj ponownie lub skontaktuj się z administratorem.');
                }
            });

        });

    </script>
}